# This file was auto-generated by cabal2nix. Please do NOT edit manually!

#let
#  cabal = haskellPackages.cabal; in
#
#{ cabal, cabalInstall_1_18_0_3, errors, haskeline, libffi, llvmGeneral, llvmGeneralPure
#, mtl, parsec, prettyShow, tasty, tastyGolden, tastyHunit
#, transformers, vector
#}:

let
  pkgs = import <nixpkgs> {};
  zlib = pkgs.zlib;
  ncurses = pkgs.ncurses;
  haskellPackages = pkgs.haskellPackages;
  cabal = haskellPackages.cabal;
  cabalInstall = haskellPackages.cabalInstall;
in cabal.mkDerivation (self: {
  pname = "llvm-codegen";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    zlib
    ncurses
    haskellPackages.errors
    haskellPackages.haskeline
    haskellPackages.libffi
    haskellPackages.llvmGeneral
    haskellPackages.llvmGeneralPure
    haskellPackages.mtl
    haskellPackages.parsec
    haskellPackages.prettyShow
    haskellPackages.transformers
    haskellPackages.vector
  ];
  buildTools = [ "cabalInstall_1_18_1_3" ];
  #testDepends = [
  #  errors libffi llvmGeneral llvmGeneralPure mtl tasty tastyGolden
  #  tastyHunit transformers vector
  #];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
